### ISSUE TITLE
文件里缺失‘vl_simplenn_tidy’函数在哪可以找到呢？

### ISSUE THREAD

**Issue by lbf523** [hli1221/imagefusion_deeplearning#1]
您好，

    我下载尝试运行您上传的程序，运行时第三行报错，找不到‘vl_simplenn_tidy’函数，请问这个问题怎么解决。

**Comment by hli1221** [comment]
你好，这个错误应该是和你的matconvet有关。请先确保你的matconvet已经正确编译，然后再运行程序。

**Comment by lbf523** [comment]
仓库里面没有您说的matconvet文件，
代码中第二行‘imagenet-vgg-verydeep-19.mat’文件我在kaggle上找的，
第三行中‘vl_simplenn_tidy’的这个应该是个函数是么？

**Comment by hli1221** [comment]
matconvet需要先下载，并编译之后才能使用。下载链接在readme中的Requirements

**Comment by lbf523** [comment]
嗯，谢谢
