### ISSUE TITLE
Are models missing?

### ISSUE THREAD

**Issue by 6xfh** [hli1221/imagefusion_deeplearning#3]
无法读取文件 'imagenet-vgg-verydeep-19.mat'。没有此类文件或目录

**Comment by hli1221** [comment]
模型文件需要自行下载，请参考 ‘readme’

**Comment by 6xfh** [comment]
谢谢您的回复



发自我的iPhone


------------------ Original ------------------

**Comment by 6xfh** [comment]
李博士；
&nbsp; &nbsp; &nbsp; 您好！我在复现你的代码时遇到一个问题，想请教您一下。在执行test_image.py操作前。将args_fusion.py中的 model_path_gray = "./models/densefuse_gray.model"替换为model_path_gray = "./models/1e2/hbFinal_epoch_4_Sun_Jul_12_00_12_01_2020_1e2.model"（hbFinal_epoch_4_Sun_Jul_12_00_12_01_2020_1e2.mode是训练得出的）。融合得出的却是一张完全黑的图像。请问这是什么原因呢？非常期待您的回复，谢谢!
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 黄冰
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2020.07.12






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hli1221/imagefusion_deeplearning"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年6月25日(星期四) 中午11:41
收件人:&nbsp;"hli1221/imagefusion_deeplearning"<imagefusion_deeplearning@noreply.github.com&gt;;
抄送:&nbsp;"黄冰"<1342814449@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hli1221/imagefusion_deeplearning] Are models missing? (#3)





 
模型文件需要自行下载，请参考 ‘readme’
