### ISSUE TITLE
请问多角度图片融合成一张图片效果如何

### ISSUE THREAD

**Issue by orangeagain** [hli1221/imagefusion_deeplearning#4]
这个开源项目太酷了,我想把它应用在3D扫描上.
看了介绍页面举的例子都是同一角度,同样大小的图片融合,请问有没有试过融合不同角度大小的图片呢?

**Comment by hli1221** [comment]
你好，感谢你对我的工作感兴趣。
目前图像融合的前提是图像先做配准，两幅图像校正之后再做融合。
所以我的这一工作还没有涉及到对不同角度的图像去融合。

**Comment by orangeagain** [comment]
不知道多曝光图像融合起来会怎样
